apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: fabmedicalft.azurecr.cn/content-web
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
         requests:
          cpu: 100m
          memory: 128Mi
